# Database Configuration
spring.application.name=printmedianenterprise
spring.datasource.url=jdbc:mysql://localhost:3306/print_median_enterprise
spring.datasource.username=root
spring.datasource.password=root

#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

app.user.url=http://localhost:4200/login

# Server IP Address - bind to all interfaces
#server.address=192.168.29.85
#server.address=10.228.29.77
server.address=0.0.0.0
server.port=8080